FROM mcr.microsoft.com/dotnet/sdk:10.0
WORKDIR /app

# Expose ports
EXPOSE 8000
EXPOSE 8001

# Install dotnet-ef tools
RUN dotnet tool install --global dotnet-ef --version 10.0.2
ENV PATH="$PATH:/root/.dotnet/tools"

# Copy project file and restore dependencies
COPY ["AdminDemo.Api.csproj", "./"]
RUN dotnet restore

# Copy everything else
COPY . .

# Run migrations and start the app with HTTPS
ENTRYPOINT ["dotnet", "watch", "run", "--urls", "https://0.0.0.0:8001;http://0.0.0.0:8000"]
